# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://RLHFlow.github.io/"
title: RLHFlow
paginate: 5
theme: ["PaperMod"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
#mainsections: ["Blog", ]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Blog
          url: posts
          weight: 5
        - name: About
          url: about/
          weight: 5
        - name: Tags
          url: tags/
          weight: 10


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "RLHFlow - Workflow of Reinforcement Learning from Human Feedback (RLHF)"
  author: RLHFlow
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
#  ShowToc: true
  # comments: false
  images: ["/about/RLHFlow-logo.png"]

  profileMode:
    enabled: false
    title: RLHFlow
    imageUrl: "/about/RLHFlow-logo.png"
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 140 # custom size
    imageHeight: 140 # custom size
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Blog
        url: posts/
      - name: About
        url: about

  homeInfoParams:
    Title: "RLHFlow"
    Content: >
      You can find open-source code, tutorials, and projects related to Reinforcement Learning from Human Feedback (RLHF) here!
      Code Repositories: <https://github.com/RLHFlow/>
      Models and Datasets: <https://huggingface.co/RLHFlow/>

  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/RLHFLow/"
    - name: huggingface
      title: Follow RLHFlow on Hugging Face
      url: "https://huggingface.co/RLHFlow"
    - name: X
      title: Share RLHFLow's Posts on X/Twitter
      url: "https://twitter.com/RLHFlow"

  editPost:
    URL: "https://github.com/RLHFlow.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

#  assets:
#    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]
math: true

markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
#markup:
#  goldmark:
#    renderer:
#      unsafe: true
#  highlight:
#    noClasses: false
#  extensions:
#    passthrough:
#      delimiters:
#        block:
#          - - \[
#            - \]
#          - - $$
#            - $$
#        inline:
#          - - \(
#            - \)
#      enable: true
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

#services:
#  instagram:
#    disableInlineCSS: true
#  twitter:
#    disableInlineCSS: true